- name: variables from play level
  host: localhost
  vars: 
    name: "harsha"
    gender: "male"
    town: "nellore"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi this is {{name}}, gender is {{grnder}}, he is from {{town}}" 

