- name: loops
  hosts: web
  become: true
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - msql
    - postfix
    
